
const html = `<!DOCTYPE html>
  <body>
    <input type="file" name="file">
    <p>This markup was generated by a Cloudflare Worker.</p>
  </body>`

export default async () => new Response(html, {
  headers: { 'content-type': 'text/html;charset=UTF-8' },
})
